### PR TITLE
#204 - Evernote bug bounty

### LINKED ISSUE #24: Importing .enex do not save folders
Is there a way to respect my evernote folder structure when importing the .enex file?

### LINKED ISSUE #185: Evernote: Titles with quotation marks are imported as Untitled Note
If evernote-notes title surrounded by quotation marks in obsidian-note doesn't have title (Untitled Note).

### LINKED ISSUE #194: [Evernote] Fails to set some notes' dates
I have just used 1.5.6 to import ENEX notes. Some of the 394 notes were not set dates according to the ones stored in the ENEX file. I end up with writing Python code to fix this. Interestingly os.utime() failed to set those dates also and I was forced to use win32file.SetFileTime().

### LINKED ISSUE #200: Evernote: imported notes do not include source links embedded in Evernote original
When material is pasted into Evernote from the web, a URL for the source page is also saved. This URL doesn't appear as a tag or within body copy, but as a separate field in the Evernote interface.

This URL isn't preserved in Obsidian pages produced by the importer.

When the same ENEX file is imported to Joplin, these URLs do appear in Note Properties.

Could the Obsidian importer be modified to include the source URL, perhaps as the first line of body copy? It's a rather important piece of data.

### LINKED ISSUE #201: [Evernote] Import loses files with the .dxf extension
Importing files from Evernote, for example with the .dxf extension, 
export works fine if the exported note is imported back into Evernote with all files in place.

### PR DESCRIPTION
**Pull request by akosbalasko**
Evernote improvements and fixes: https://github.com/obsidianmd/obsidian-importer/issues/204

#190  - Fixed
#200 - Implemented
#26 - Fixed
#201  - Fixed
#24 - Implemented, "@@@" used as delimiter between notebookstack's and notebook's name in the enex file
#187 - Cannot be implemented phisically, possible solution would be to ask the users to flat nested tags by '/' before the conversion within Evernote
#194  - Cannot reproduce, possible reason patched
#184 - Cannot reproduce, reporter asked to close
#185 - Cannot  reproduce, no hints from reporter

+1 -  Title removed from the converted note's body

### CODE REVIEW

**Comment by kepano** [comment]
@akosbalasko thanks! Will review shortly. Two more things:

1. Can you submit a PR to the [obsidian-help](https://github.com/obsidianmd/obsidian-help) repo with additional detail on the [Evernote import instructions](https://github.com/obsidianmd/obsidian-help/blob/master/en/Import%20notes/Import%20from%20Evernote.md) for handling tags/folders?
2. Can you reply here stating `I have read the CLA agreement and I hereby sign the CLA.` per our [contribution guidelines](https://github.com/obsidianmd/obsidian-importer/blob/master/CONTRIBUTING.md)?

File: src/formats/yarle/utils/filename-utils.ts [hunk 1]
```diff
@@ -37,7 +37,7 @@ export const getResourceFileProperties = (workDir: string, resource: any): Resou
 
 	if (resource['resource-attributes'] && resource['resource-attributes']['file-name']) {
 		const fileNamePrefix = resource['resource-attributes']['file-name'].substr(0, 50);
-		fileName = fileNamePrefix.split('.')[0];
+		fileName = fileNamePrefix.includes('.') ? fileNamePrefix.split('.').slice(0, -1).join('.') : fileNamePrefix;
```
Comment (tgrosinger) [inline src/formats/yarle/utils/filename-utils.ts:40]: I think we could make this a little more efficient and avoid searching through the string multiple times:

```
const lastIdx = fileNamePrefix.lastIndexOf('.');
fileName = lastIdx !== -1
    ? fileNamePrefix.slice(0, lastIdx)
    : fileNamePrefix;
```

File: src/formats/yarle/utils/templates/default-template.ts [hunk 2]
```diff
@@ -1,5 +1,7 @@
-const tagBlock = '{tags-array-block}---\ntags: {tags-array}\n---\n{end-tags-array-block}';
+const frontmatterDelimiter = '---\n';
+const sourceBlock = '{source-url-block}\nsource: {source-url}\n\n{end-source-url-block}';
```
Comment (tgrosinger) [inline src/formats/yarle/utils/templates/default-template.ts]: Will this cause the `source` property to be present even for files that do not have a source specified?

File: src/formats/yarle/utils/templates/checker-functions.ts [hunk 3]
```diff
@@ -40,7 +41,8 @@ export const hasSourceURLInTemplate = (templateContent: string): boolean => {
 };
 export const hasAnyTagsInTemplate = (templateContent: string): boolean => {
 	return (hasItemInTemplate(TAGS, templateContent)
-		|| hasItemInTemplate(YAMLARRAYTAGS, templateContent));
```
Comment (tgrosinger) [inline src/formats/yarle/utils/templates/checker-functions.ts:43]: Should we remove the various bits of code for array tags now? It looks like they are unused?

File: src/formats/yarle/utils/templates/default-template.ts [hunk 4]
```diff
@@ -1,7 +1,6 @@
 const frontmatterDelimiter = '---\n';
 const sourceBlock = '{source-url-block}source: {source-url}{end-source-url-block}\n';
 const tagBlock = '{tags-yaml-list-block}\ntags: {tags-yaml-list}\n\n{end-tags-yaml-list-block}';
-const titleBlock = '{title-block}# {title}\n\n{end-title-block}';
```
Comment (tgrosinger) [inline src/formats/yarle/utils/templates/default-template.ts:2]: Is there an issue corresponding to this change? I'm not sure if this is change we wanted to make.

File: src/formats/yarle/process-resources.ts [hunk 5]
```diff
@@ -77,9 +77,13 @@ const processResource = (workDir: string, resource: any): any => {
 	// Skip unknown type as we don't know how to handle
 	// Source: https://dev.evernote.com/doc/articles/data_structure.php
 	// "The default type "application/octet-stream" should be used if a more specific type is not known."
-	if (resource.mime === 'application/octet-stream') {
+	// Update:
```
Comment (tgrosinger) [inline src/formats/yarle/process-resources.ts:80]: @lishid or @ericaxu, does this seem reasonable to you? I'm not too familiar with Yarle.

File: src/formats/yarle/utils/folder-utils.ts [hunk 6]
```diff
@@ -119,7 +120,20 @@ export const clearResourceDir = (note: any): void => {
...
+export const handleNotebookstacks = (enex: PickedFile, options: YarleOptions): void => {
+	const notebookFolderNames = enex.basename.split('@@@');
+	let notebookName = notebookFolderNames.pop();
+	if (!notebookName){
+		notebookName = enex.basename;
+	}
+	fs.mkdirSync(path.join(options.outputDir, ...notebookFolderNames), { recursive: true });
+	enex.fullpath = enex.fullpath.replace(enex.basename, notebookName || enex.basename);
+	enex.name = enex.name.replace(enex.basename, notebookName || enex.basename);
+	options.outputDir = [options.outputDir, ...notebookFolderNames].join(options.pathSeparator);
```
Comment (tgrosinger) [inline src/formats/yarle/utils/folder-utils.ts:132]: Will this behave as expected if there are multiple files being imported?

It looks like if we modify the outputDir here it will affect subsequent files being imported.

**Review by tgrosinger — CHANGES_REQUESTED** [review]

File: src/formats/yarle/utils/folder-utils.ts (hunk 6 above)
Comment (akosbalasko) [reply src/formats/yarle/utils/folder-utils.ts:132]: Nope, because I save the original outputDir  at line 187 in yarle.ts and restore after the conversion (line 201).

File: src/formats/yarle/utils/templates/checker-functions.ts (hunk 3 above)
Comment (akosbalasko) [reply src/formats/yarle/utils/templates/checker-functions.ts:43]: well, yeah, I was thinking on it, as you wish, I think the whole array tags in yaml together with its templates is currently not used. @lishid any suggestion?

File: src/formats/yarle/utils/templates/default-template.ts (hunk 4 above)
Comment (akosbalasko) [reply src/formats/yarle/utils/templates/default-template.ts:2]: no dedicated issue for this, I discussed it with @kepano here: https://github.com/obsidianmd/obsidian-importer/issues/204#issuecomment-1915558518

File: src/formats/yarle/utils/filename-utils.ts [hunk 7]
```diff
@@ -37,7 +37,10 @@ export const getResourceFileProperties = (workDir: string, resource: any): Resou
 
 	if (resource['resource-attributes'] && resource['resource-attributes']['file-name']) {
 		const fileNamePrefix = resource['resource-attributes']['file-name'].substr(0, 50);
-		fileName = fileNamePrefix.split('.')[0];
+		const lastIdx = fileNamePrefix.lastIndexOf('.');
```
Comment (akosbalasko) [inline src/formats/yarle/utils/filename-utils.ts:40]: thx @tgrosinger , I applied your solution.

File: src/formats/yarle/utils/templates/default-template.ts (hunk 2 above)
Comment (akosbalasko) [reply src/formats/yarle/utils/templates/default-template.ts]: Nope, it is removed from the template automatically if no source property specified in the note data structure

File: src/formats/yarle/utils/templates/default-template.ts (hunk 4 above)
Comment (tgrosinger) [reply src/formats/yarle/utils/templates/default-template.ts:2]: Ah great, thank you.

File: src/formats/yarle/utils/folder-utils.ts (hunk 6 above)
Comment (tgrosinger) [reply src/formats/yarle/utils/folder-utils.ts:132]: I believe that's just saving a reference to the object, but that's the same object that will be modified here.

Comment (tgrosinger) [reply src/formats/yarle/utils/folder-utils.ts:132]: Ah, sorry I misread and thought you were storing the full options object.
Thank you for clarifying for me!

**Review by tgrosinger — APPROVED** [review]
Looks good to me, pending the remaining comments for @lishid.

**Comment by akosbalasko** [comment]
Any updates on this @kepano @lishid @ericaxu ?

File: src/formats/yarle/utils/templates/checker-functions.ts (hunk 3 above)
Comment (lishid) [reply src/formats/yarle/utils/templates/checker-functions.ts:43]: I think removing it would be best, thanks!

**Comment by lishid** [comment]
Sorry I am late!

File: src/formats/yarle/utils/folder-utils.ts [hunk 8]
```diff
@@ -119,7 +120,20 @@ export const clearResourceDir = (note: any): void => {
...
 
-export const setPaths = (enexSource: PickedFile): void => {
+export const handleNotebookstacks = (enex: PickedFile, options: YarleOptions): void => {
+	const notebookFolderNames = enex.basename.split('@@@');
+	let notebookName = notebookFolderNames.pop();
+	if (!notebookName){
+		notebookName = enex.basename;
+	}
+	fs.mkdirSync(path.join(options.outputDir, ...notebookFolderNames), { recursive: true });
+	enex.fullpath = enex.fullpath.replace(enex.basename, notebookName || enex.basename);
```
[the remark this answers is not in the document]
Comment (akosbalasko) [reply src/formats/yarle/utils/folder-utils.ts:130]: > These aren't meant to be modified. PickedFile represents a file picked from the operating system. If we need to work on a different set of names over the original file then we should use a proper data structure to make this clear.

@lishid But in this case, it would mean just to clone the current PickedFile, changing its props and use it instead of that we got from outside, or not? 

> Also, this wouldn't work if the full path contains a piece that is identical to the enex basename. For example, C:/Evernote/Files/Evernote.enex would only get the first "Evernote" replaced instead of the intended second.

Good point I'll resolve it.

File: src/formats/yarle/utils/folder-utils.ts (hunk 6 above)
Comment (akosbalasko) [reply src/formats/yarle/utils/folder-utils.ts:132]: @lishid ok, let me try to improve it.

File: src/formats/yarle/utils/folder-utils.ts (hunk 8 above)
[the remark this answers is not in the document]
Comment (lishid) [reply src/formats/yarle/utils/folder-utils.ts:130]: > @lishid But in this case, it would mean just to clone the current PickedFile, changing its props and use it instead of that we got from outside, or not?

Can you explain the use case here? If I'm understanding it correctly you'd like to specify a different title/output path for the same input file, right? In that case I would suggest passing this additional information over to the code that uses it (through an object or function parameters) to clearly indicate that it's the supposed output path.

[the remark this answers is not in the document]
Comment (akosbalasko) [reply src/formats/yarle/utils/folder-utils.ts]: @lishid yeah, that would be the use case, and I used to use options object would to store these kind of info. Now I cleaned a code a bit around notebook stacks, hope it looks better for you too.

File: src/formats/yarle/utils/templates/checker-functions.ts (hunk 3 above)
Comment (akosbalasko) [reply src/formats/yarle/utils/templates/checker-functions.ts:43]: @lishid removed

File: src/formats/yarle/utils/folder-utils.ts [hunk 9]
```diff
@@ -118,8 +120,42 @@ export const clearResourceDir = (note: any): void => {
...
+};
+
+
+export const getNotebookStackedEnex = (baseEnex: PickedFile ): NodePickedFile => {
+	if (!(baseEnex instanceof NodePickedFile)) throw new Error('Evernote import currently only works on desktop');
+
+	const { notebookName } =  getNotebookNameAndFolderNames(baseEnex.basename);
+
+	const stackedPickedFile = new NodePickedFile((baseEnex as NodePickedFile).filepath);
+	stackedPickedFile.fullpath = replaceLastOccurrenceInString(baseEnex.fullpath, baseEnex.basename, notebookName || baseEnex.basename);
```
[the remark this answers is not in the document]
Comment (akosbalasko) [reply src/formats/yarle/utils/folder-utils.ts]: @lishid Ohh, okay, now I get it, thanks for the clarification! Changes made to make it work with untouchable NodePickedFiles. :)

[the remark this answers is not in the document]
Comment (lishid) [reply src/formats/yarle/utils/folder-utils.ts]: As I understand it, what's happening here is that we are finding some code down the line that uses these fields, and we'd like to change their behavior to use a different names/paths. Doing it this way is a "shortcut"; while it results in minimal amount of changes, it also makes the code much more confusing. Similar to what I said in the other comment, when you have a field that is defined to mean one thing, and you use it for a slightly different purpose (and thus modify the contents to fit your alternative needs), it creates a chance of confusion, or at the very least, forces the reader to "keep in mind" these extra concerns. This is often where bugs can slip in, especially if there are many different little things one needed to keep in mind when working with the code.

Usually the best way to do this is being more explicit with the code to say what you intend with the variables and fields. Passing additional vars with names that indicate what they do (or is intended for) helps a lot.

[the remark this answers is not in the document]
Comment (lishid) [reply src/formats/yarle/utils/folder-utils.ts]: Yup the new changes works for me.

**Review by lishid — APPROVED** [review]
Code looks ok to me. Might be worth doing one final pass of the auto formatter.

File: src/formats/yarle/utils/folder-utils.ts (hunk 9 above)
[the remark this answers is not in the document]
Comment (akosbalasko) [reply src/formats/yarle/utils/folder-utils.ts]: @lishid , sorry, I had a bad feeling about this, so I tried to improve the code further, introduced a couple of new functions to decrease the level of the possible confusion. Hope it looks better for you too.

[the remark this answers is not in the document]
Comment (lishid) [reply src/formats/yarle/utils/folder-utils.ts]: Thanks. I would say don't worry too much about it. Yarle is unfortunately written in a very different paradigm of programming than the rest of the importer. It uses global singleton objects and naked functions with context being passed sometimes, set in the global object at other times.

I decided not to invest too much effort to rewrite yarle as it would not be worth the time for a functionally equivalent package.

[the remark this answers is not in the document]
Comment (akosbalasko) [reply src/formats/yarle/utils/folder-utils.ts]: okay then we can move forward with it, right?

**Comment by tgrosinger** [comment]
Looks good to me.
